Esilky  unit tests#378
Watson-Personal-Assistant/AudioClientSampleCodeJava pull request #4
Opened 2018-05-29 08:42 UTC by esilky

This:
* adds a 'main' package for the 'Driver' class to be in (to conform to the Java spec and to allow for unit testing).
* makes the <<default-package>>.Driver.main method create a Driver object and use it to run the client.  This allows the start scripts to continue to run correctly without specifying a package (helpful in general).
* adds an initial collection of JUnit tests
* slightly refactors some classes to allow them to be tests
* adds some useful methods to the StatusIndicator interface
* fixes a problem with the StatusConsole class that wasn't found until implementing the unit tests
* adds JUnit foundation to the project in the form of:
** JUnit test categories (these allow tests to be categorized as 'general', 'slow-running', other...
** JUnit Test Suite base class - where test classes can be registered to be included in Test Suites
** JUnit Test Suite All - runs all of the unit tests registered in the base class
** JUnit Test Suite General - runs all of the 'general' (non long-running) tests registered in the base class

These tests can be executed from within Eclipse by using the 'Run As - JUnit Test' right-click menu command on any of the test classes or the 'Suite' classes (in the _junitTests folder).

<< ToDo - implement running the tests from a Maven command >>

2018-05-29 08:47 UTC, esilky commented
Sorry if I'm doing this wrong... I've worked with SCC for decades, but I'm new to Git & GitHub.

This includes (or seems to include) changes from the previous two pull requests I submitted.  If that is correct - great!  If not, can you give me pointers on what I need to do to limit the 'pull' to just the changes in this branch. (other SCC systems I've worked with would only list the changes that were made in this branch)

2018-05-29 08:49 UTC, esilky commented
I have some changes for enabling the Maven project to run the tests, but I'm going to wait to create an issue and branch for it until these get approved/merged.

2018-06-03 08:20 UTC, erezbi commented
@esilky I think once we merge the previous PRs, and you pull from master into this branch, then only the new changes should be visible here.
Also, we create a branch for each task. So each PR should have little changes in it, and probably they will not conflict. You should work based on master in the different branches that you do, and not based on each of your branches, if possible. Does this make sense?

2018-06-04 17:47 UTC, esilky commented
@erezbi - that makes sense, I think the problem might be with the time-zone delay. When I submit a pull, I then move on to the next task.  To do that, I create a new branch - but the previous branch changes are included until they are accepted and merged (at least that is what it seems). So, if I want to submit the next task, it includes the previous changes (or seems to).

Again, I have worked with almost a dozen SCC Systems, but not very much with Git (and it is not intuitive - in my opinion).

2018-06-04 17:52 UTC, esilky commented
@erezbi - If I work from master, then it does not include the changes I made to-date. In some cases that could be fine - but if I've made changes to (say) logging (Log4J) that have not been accepted yet, but I want to use that Log4J functionality for logging of 'performance' I can't simply work from master.

2018-06-05 11:08 UTC, erezbi commented
@esilky you are right. We usually are able to work based on master. You can work based on other branch, I think that if it accepted before the second one, then there will not be a conflict. But until the first one is accepted, the second will show more changes than really exist there.

2018-06-06 18:22 UTC, esilky commented
@erezbi Okay, that makes sense.  I was just a bit confused why all of these changes were showing up.  Other SCCS I've worked with have not displayed it that way.

2018-06-06 18:26 UTC, esilky commented
@erezbi @arivatibm - Is there anything needed from me to get this merged?

2018-06-07 06:38 UTC, arivatibm requested changes

2018-06-07 06:38 UTC, arivatibm commented on src/main/java/wa/client/Client.java
> +                        IAMAccessToken = getIAMAccessToken(keyIAMAPI);
same comment as in the previous pull request - change name to iamApiKey

2018-06-07 06:38 UTC, arivatibm commented
Please ask Ramesh to test this after you are done with the code fix

2018-06-07 06:45 UTC, arivatibm commented
QA testing by Ramesh
I've asked him to do it just now
 
                                                                        Regards,
                         
                        Ari Volcoff                        Research Staff Member                        Watson Assistant Solutions , IoT And Wearables                        IBM - Haifa Research Lab                                                                         
                                                                                                                                                        Mobile: +972-58-4168357 | Phone: +972-4-8281319                        E-mail: ARIV@il.ibm.com                        LinkedIn: https://il.linkedin.com/in/avolcoff                                                
 
 
----- Original message -----From: Ed Silky <notifications@github.com>To: Watson-Personal-Assistant/AudioClientSampleCodeJava <AudioClientSampleCodeJava@noreply.github.com>Cc: arivatibm <ariv@il.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [Watson-Personal-Assistant/AudioClientSampleCodeJava] Esilky unit tests#378 (#4)Date: Wed, Jun 6, 2018 9:26 PM 
@erezbi @arivatibm - Is there anything needed from me to get this merged?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  
 

2018-06-12 07:57 UTC, arivatibm commented
@esilky  told Ramesh he needs to make some additional fixes 
@erezbi FYI

2018-06-28 18:25 UTC, esilky commented on src/main/java/wa/client/Client.java
> +                        IAMAccessToken = getIAMAccessToken(keyIAMAPI);
@arivatibm Changed to iamApiKey per request.

2018-06-28 18:33 UTC, esilky commented
@rameshupadhyaper This is tested by:
- opening the project in Eclipse
- use Enterprise Explorer and open the tree at `testsrc/main/java : _junitTests`
- right click on `JUnitTestSuite_All.java` and select 'Run as > JUnit Test'
- open the JUnit view (might need to open from Window>Show View
- check that 5/5 tests ran with 0 errors and 0 failures (green bar)
- do the same for `JUnitTestSuite_General.java` and verify that 4/4 tests ran without errors/failures

2018-06-30 00:01 UTC, esilky commented
@rameshupadhyaper please let @arivatibm know when you have finished your testing.

@arivatibm do you need to do anything to clear your review? I made the requested changes.

2018-07-01 11:31 UTC, arivatibm approved these changes

2018-07-01 11:33 UTC, arivatibm commented
@esilky there are some merge conflicts - can you resolve them by merging the master into your feature branch?

2018-07-07 22:37 UTC, esilky commented
@arivatibm @erezbi the latest master is merged in.  There shouldn't be any conflicts.

2018-07-08 07:32 UTC, erezbi commented
@esilky I see you made more commits. Did @rameshupadhyaper test the PR after this last commit
(eb77668 above)?

2018-07-09 00:05 UTC, esilky commented
These were part of the merge from master into the branch for this PR.
@rameshupadhyaper have you tested?

2018-07-10 05:48 UTC, rameshupadhyaper commented
@esilky 
@erezbi 
Tested in window machine.
Working fine as per requirement.

2018-07-10 06:03 UTC, merged